// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, action, metadata)
VALUES ($1, $2, $3)
`

type InsertAuditLogParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Action   string      `json:"action"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog, arg.UserID, arg.Action, arg.Metadata)
	return err
}
