services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ajudafio_api
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - .env
    volumes:
      # Joga o .env fisicamente para onde o binário está rodando
      - ./.env:/app/.env
