FROM golang:1.26-alpine

RUN apk add --no-cache gcc musl-dev
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

EXPOSE 8080 2345

CMD ["dlv", "debug", "./cmd/main.go", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "--continue"]
