ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_role;

UPDATE users SET role = CASE role
  WHEN 'CLIENT'       THEN 'FAMILY_CLIENT'
  WHEN 'PROFESSIONAL' THEN 'HEALTH_CAREPROVIDER'
  WHEN 'ADMIN'        THEN 'PLATFORM_ADMIN'
  ELSE role
END;

ALTER TABLE users ALTER COLUMN role SET DEFAULT 'FAMILY_CLIENT';

ALTER TABLE users ADD CONSTRAINT chk_role CHECK (
  role IN ('FAMILY_CLIENT', 'HEALTH_CAREPROVIDER', 'FINANCIAL_SPONSOR', 'PLATFORM_ADMIN')
);
