ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_role;

UPDATE users SET role = CASE role
  WHEN 'FAMILY_CLIENT'       THEN 'CLIENT'
  WHEN 'HEALTH_CAREPROVIDER' THEN 'PROFESSIONAL'
  WHEN 'PLATFORM_ADMIN'      THEN 'ADMIN'
  WHEN 'FINANCIAL_SPONSOR'   THEN 'CLIENT'
  ELSE role
END;

ALTER TABLE users ALTER COLUMN role SET DEFAULT 'CLIENT';

ALTER TABLE users ADD CONSTRAINT chk_role CHECK (role IN ('CLIENT','PROFESSIONAL','ADMIN'));
