// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: professional.sql

package professionalpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProfessionals = `-- name: CountProfessionals :one
SELECT COUNT(*)
FROM professionals p
WHERE
    ($1::text IS NULL OR EXISTS (
        SELECT 1 FROM addresses a WHERE a.user_id = p.user_id AND a.city = $1::text
    ))
    AND ($2::text IS NULL OR EXISTS (
        SELECT 1 FROM addresses a WHERE a.user_id = p.user_id AND a.state = $2::text
    ))
    AND ($3::text[] IS NULL OR EXISTS (
        SELECT 1 FROM availabilities av WHERE av.professional_id = p.id AND av.day_of_week = ANY($3::text[])
    ))
    AND ($4::text[] IS NULL OR EXISTS (
        SELECT 1 FROM availabilities av WHERE av.professional_id = p.id AND av.shift = ANY($4::text[])
    ))
`

type CountProfessionalsParams struct {
	City      *string  `json:"city"`
	State     *string  `json:"state"`
	DayOfWeek []string `json:"day_of_week"`
	Shift     []string `json:"shift"`
}

func (q *Queries) CountProfessionals(ctx context.Context, arg CountProfessionalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProfessionals,
		arg.City,
		arg.State,
		arg.DayOfWeek,
		arg.Shift,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfessional = `-- name: CreateProfessional :one
INSERT INTO professionals (
  user_id,
  license_number,
  category,
  years_of_experience,
  resume,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, user_id, license_number, category, years_of_experience, verified, resume, metadata, created_at, updated_at
`

type CreateProfessionalParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	LicenseNumber     *string     `json:"license_number"`
	Category          string      `json:"category"`
	YearsOfExperience *int32      `json:"years_of_experience"`
	Resume            *string     `json:"resume"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateProfessional(ctx context.Context, arg CreateProfessionalParams) (Professional, error) {
	row := q.db.QueryRow(ctx, createProfessional,
		arg.UserID,
		arg.LicenseNumber,
		arg.Category,
		arg.YearsOfExperience,
		arg.Resume,
		arg.Metadata,
	)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfessional = `-- name: DeleteProfessional :exec
DELETE FROM professionals
WHERE id = $1
`

func (q *Queries) DeleteProfessional(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfessional, id)
	return err
}

const getProfessionalByID = `-- name: GetProfessionalByID :one
SELECT p.id, p.user_id, p.license_number, p.category, p.years_of_experience, p.verified, p.resume, p.metadata, p.created_at, p.updated_at, u.name AS user_name, u.avatar_url AS user_avatar_url, u.email AS user_email, u.role AS user_role
FROM professionals p
INNER JOIN users u ON p.user_id = u.id
WHERE p.id = $1
LIMIT 1
`

type GetProfessionalByIDRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	LicenseNumber     *string          `json:"license_number"`
	Category          string           `json:"category"`
	YearsOfExperience *int32           `json:"years_of_experience"`
	Verified          bool             `json:"verified"`
	Resume            *string          `json:"resume"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	UserName          string           `json:"user_name"`
	UserAvatarUrl     *string          `json:"user_avatar_url"`
	UserEmail         string           `json:"user_email"`
	UserRole          string           `json:"user_role"`
}

func (q *Queries) GetProfessionalByID(ctx context.Context, id pgtype.UUID) (GetProfessionalByIDRow, error) {
	row := q.db.QueryRow(ctx, getProfessionalByID, id)
	var i GetProfessionalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserAvatarUrl,
		&i.UserEmail,
		&i.UserRole,
	)
	return i, err
}

const getProfessionalByUserID = `-- name: GetProfessionalByUserID :one
SELECT id, user_id, license_number, category, years_of_experience, verified, resume, metadata, created_at, updated_at
FROM professionals
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetProfessionalByUserID(ctx context.Context, userID pgtype.UUID) (Professional, error) {
	row := q.db.QueryRow(ctx, getProfessionalByUserID, userID)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfessionals = `-- name: ListProfessionals :many
SELECT
    p.id,
    p.user_id,
    p.license_number,
    p.category,
    p.years_of_experience,
    p.verified,
    p.resume,
    p.metadata,
    p.created_at,
    p.updated_at,
    u.name AS user_name,
    u.avatar_url AS user_avatar_url,
    u.email AS user_email,
    u.role AS user_role
FROM professionals p
LEFT JOIN users u ON p.user_id = u.id
WHERE
    ($1::text IS NULL OR EXISTS (
        SELECT 1 FROM addresses a WHERE a.user_id = p.user_id AND a.city = $1::text
    ))
    AND ($2::text IS NULL OR EXISTS (
        SELECT 1 FROM addresses a WHERE a.user_id = p.user_id AND a.state = $2::text
    ))
    AND ($3::text[] IS NULL OR EXISTS (
        SELECT 1 FROM availabilities av WHERE av.professional_id = p.id AND av.day_of_week = ANY($3::text[])
    ))
    AND ($4::text[] IS NULL OR EXISTS (
        SELECT 1 FROM availabilities av WHERE av.professional_id = p.id AND av.shift = ANY($4::text[])
    ))
ORDER BY p.created_at DESC
LIMIT $6 OFFSET $5
`

type ListProfessionalsParams struct {
	City      *string  `json:"city"`
	State     *string  `json:"state"`
	DayOfWeek []string `json:"day_of_week"`
	Shift     []string `json:"shift"`
	OffsetVal int32    `json:"offset_val"`
	LimitVal  int32    `json:"limit_val"`
}

type ListProfessionalsRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	LicenseNumber     *string          `json:"license_number"`
	Category          string           `json:"category"`
	YearsOfExperience *int32           `json:"years_of_experience"`
	Verified          bool             `json:"verified"`
	Resume            *string          `json:"resume"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	UserName          *string          `json:"user_name"`
	UserAvatarUrl     *string          `json:"user_avatar_url"`
	UserEmail         *string          `json:"user_email"`
	UserRole          *string          `json:"user_role"`
}

func (q *Queries) ListProfessionals(ctx context.Context, arg ListProfessionalsParams) ([]ListProfessionalsRow, error) {
	rows, err := q.db.Query(ctx, listProfessionals,
		arg.City,
		arg.State,
		arg.DayOfWeek,
		arg.Shift,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfessionalsRow
	for rows.Next() {
		var i ListProfessionalsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LicenseNumber,
			&i.Category,
			&i.YearsOfExperience,
			&i.Verified,
			&i.Resume,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserAvatarUrl,
			&i.UserEmail,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfessional = `-- name: UpdateProfessional :one
UPDATE professionals SET
  license_number      = COALESCE($1, license_number),
  category            = COALESCE($2, category),
  years_of_experience = COALESCE($3, years_of_experience),
  verified            = COALESCE($4, verified),
  resume              = COALESCE($5, resume),
  metadata            = COALESCE($6, metadata),
  updated_at          = NOW()
WHERE id = $7
RETURNING id, user_id, license_number, category, years_of_experience, verified, resume, metadata, created_at, updated_at
`

type UpdateProfessionalParams struct {
	LicenseNumber     *string     `json:"license_number"`
	Category          *string     `json:"category"`
	YearsOfExperience *int32      `json:"years_of_experience"`
	Verified          *bool       `json:"verified"`
	Resume            *string     `json:"resume"`
	Metadata          []byte      `json:"metadata"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProfessional(ctx context.Context, arg UpdateProfessionalParams) (Professional, error) {
	row := q.db.QueryRow(ctx, updateProfessional,
		arg.LicenseNumber,
		arg.Category,
		arg.YearsOfExperience,
		arg.Verified,
		arg.Resume,
		arg.Metadata,
		arg.ID,
	)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
