// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: professional.sql

package professionalpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfessional = `-- name: CreateProfessional :one
INSERT INTO professionals (
  user_id,
  license_number,
  category,
  years_of_experience,
  resume,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, user_id, license_number, category, years_of_experience, verified, resume, metadata, created_at, updated_at
`

type CreateProfessionalParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	LicenseNumber     *string     `json:"license_number"`
	Category          string      `json:"category"`
	YearsOfExperience *int32      `json:"years_of_experience"`
	Resume            *string     `json:"resume"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateProfessional(ctx context.Context, arg CreateProfessionalParams) (Professional, error) {
	row := q.db.QueryRow(ctx, createProfessional,
		arg.UserID,
		arg.LicenseNumber,
		arg.Category,
		arg.YearsOfExperience,
		arg.Resume,
		arg.Metadata,
	)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfessional = `-- name: DeleteProfessional :exec
DELETE FROM professionals
WHERE id = $1
`

func (q *Queries) DeleteProfessional(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfessional, id)
	return err
}

const getProfessionalByID = `-- name: GetProfessionalByID :one
SELECT id, user_id, license_number, category, years_of_experience, verified, resume, metadata, created_at, updated_at
FROM professionals
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProfessionalByID(ctx context.Context, id pgtype.UUID) (Professional, error) {
	row := q.db.QueryRow(ctx, getProfessionalByID, id)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfessionalByUserID = `-- name: GetProfessionalByUserID :one
SELECT id, user_id, license_number, category, years_of_experience, verified, resume, metadata, created_at, updated_at
FROM professionals
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetProfessionalByUserID(ctx context.Context, userID pgtype.UUID) (Professional, error) {
	row := q.db.QueryRow(ctx, getProfessionalByUserID, userID)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfessionals = `-- name: ListProfessionals :many
SELECT DISTINCT
    p.id,
    p.user_id,
    p.license_number,
    p.category,
    p.years_of_experience,
    p.verified,
    p.resume,
    p.metadata,
    p.created_at,
    p.updated_at
FROM professionals p
LEFT JOIN addresses a ON p.user_id = a.user_id
LEFT JOIN availabilities av ON p.id = av.professional_id
WHERE
    ($1::text IS NULL OR a.city = $1::text)
    AND ($2::text IS NULL OR a.state = $2::text)
    AND ($3::text[] IS NULL OR av.day_of_week = ANY($3::text[]))
    AND ($4::text[] IS NULL OR av.shift = ANY($4::text[]))
ORDER BY p.created_at DESC
`

type ListProfessionalsParams struct {
	City      *string  `json:"city"`
	State     *string  `json:"state"`
	DayOfWeek []string `json:"day_of_week"`
	Shift     []string `json:"shift"`
}

func (q *Queries) ListProfessionals(ctx context.Context, arg ListProfessionalsParams) ([]Professional, error) {
	rows, err := q.db.Query(ctx, listProfessionals,
		arg.City,
		arg.State,
		arg.DayOfWeek,
		arg.Shift,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Professional
	for rows.Next() {
		var i Professional
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LicenseNumber,
			&i.Category,
			&i.YearsOfExperience,
			&i.Verified,
			&i.Resume,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfessional = `-- name: UpdateProfessional :one
UPDATE professionals SET
  license_number      = COALESCE($1, license_number),
  category            = COALESCE($2, category),
  years_of_experience = COALESCE($3, years_of_experience),
  verified            = COALESCE($4, verified),
  resume              = COALESCE($5, resume),
  metadata            = COALESCE($6, metadata),
  updated_at          = NOW()
WHERE id = $7
RETURNING id, user_id, license_number, category, years_of_experience, verified, resume, metadata, created_at, updated_at
`

type UpdateProfessionalParams struct {
	LicenseNumber     *string     `json:"license_number"`
	Category          *string     `json:"category"`
	YearsOfExperience *int32      `json:"years_of_experience"`
	Verified          *bool       `json:"verified"`
	Resume            *string     `json:"resume"`
	Metadata          []byte      `json:"metadata"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProfessional(ctx context.Context, arg UpdateProfessionalParams) (Professional, error) {
	row := q.db.QueryRow(ctx, updateProfessional,
		arg.LicenseNumber,
		arg.Category,
		arg.YearsOfExperience,
		arg.Verified,
		arg.Resume,
		arg.Metadata,
		arg.ID,
	)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LicenseNumber,
		&i.Category,
		&i.YearsOfExperience,
		&i.Verified,
		&i.Resume,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
