// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: appointment.sql

package appointmentpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkOverlap = `-- name: CheckOverlap :one
SELECT EXISTS (
  SELECT 1 FROM appointments
  WHERE professional_id = $1
    AND date = $2
    AND status <> 'CANCELLED'
    AND NOT (end_time <= $3 OR start_time >= $4)
) AS has_overlap
`

type CheckOverlapParams struct {
	ProfessionalID pgtype.UUID `json:"professional_id"`
	Date           pgtype.Date `json:"date"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
}

func (q *Queries) CheckOverlap(ctx context.Context, arg CheckOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkOverlap,
		arg.ProfessionalID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
	)
	var has_overlap bool
	err := row.Scan(&has_overlap)
	return has_overlap, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
  contract_id, client_id, professional_id,
  date, start_time, end_time,
  zip_code, address_line, number, complement, district, city, state, reference
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, contract_id, client_id, professional_id, date, start_time, end_time, status, zip_code, address_line, number, complement, district, city, state, reference, version, created_at, updated_at
`

type CreateAppointmentParams struct {
	ContractID     pgtype.UUID `json:"contract_id"`
	ClientID       pgtype.UUID `json:"client_id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	Date           pgtype.Date `json:"date"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	ZipCode        string      `json:"zip_code"`
	AddressLine    string      `json:"address_line"`
	Number         string      `json:"number"`
	Complement     *string     `json:"complement"`
	District       string      `json:"district"`
	City           string      `json:"city"`
	State          string      `json:"state"`
	Reference      *string     `json:"reference"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ContractID,
		arg.ClientID,
		arg.ProfessionalID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.ZipCode,
		arg.AddressLine,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.Reference,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id)
	return err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, contract_id, client_id, professional_id, date, start_time, end_time, status, zip_code, address_line, number, complement, district, city, state, reference, version, created_at, updated_at
FROM appointments
WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentsByClientID = `-- name: GetAppointmentsByClientID :many
SELECT id, contract_id, client_id, professional_id, date, start_time, end_time, status, zip_code, address_line, number, complement, district, city, state, reference, version, created_at, updated_at
FROM appointments
WHERE client_id = $1
ORDER BY date, start_time
`

func (q *Queries) GetAppointmentsByClientID(ctx context.Context, clientID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.ZipCode,
			&i.AddressLine,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.Reference,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByContractID = `-- name: GetAppointmentsByContractID :many
SELECT id, contract_id, client_id, professional_id, date, start_time, end_time, status, zip_code, address_line, number, complement, district, city, state, reference, version, created_at, updated_at
FROM appointments
WHERE contract_id = $1
ORDER BY date, start_time
`

func (q *Queries) GetAppointmentsByContractID(ctx context.Context, contractID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByContractID, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.ZipCode,
			&i.AddressLine,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.Reference,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByProfessionalID = `-- name: GetAppointmentsByProfessionalID :many
SELECT id, contract_id, client_id, professional_id, date, start_time, end_time, status, zip_code, address_line, number, complement, district, city, state, reference, version, created_at, updated_at
FROM appointments
WHERE professional_id = $1
ORDER BY date, start_time
`

func (q *Queries) GetAppointmentsByProfessionalID(ctx context.Context, professionalID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.ZipCode,
			&i.AddressLine,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.Reference,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET status     = $1,
    version    = version + 1,
    updated_at = NOW()
WHERE id = $2 AND version = $3
RETURNING id, contract_id, client_id, professional_id, date, start_time, end_time, status, zip_code, address_line, number, complement, district, city, state, reference, version, created_at, updated_at
`

type UpdateAppointmentStatusParams struct {
	Status  string      `json:"status"`
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatus, arg.Status, arg.ID, arg.Version)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
