// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package appointmentpostgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	ContractID  pgtype.UUID      `json:"contract_id"`
	ZipCode     string           `json:"zip_code"`
	AddressLine string           `json:"address_line"`
	Number      string           `json:"number"`
	Complement  *string          `json:"complement"`
	District    string           `json:"district"`
	City        string           `json:"city"`
	State       string           `json:"state"`
	Reference   *string          `json:"reference"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Appointment struct {
	ID             pgtype.UUID        `json:"id"`
	ContractID     pgtype.UUID        `json:"contract_id"`
	ClientID       pgtype.UUID        `json:"client_id"`
	ProfessionalID pgtype.UUID        `json:"professional_id"`
	Date           pgtype.Date        `json:"date"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Status         string             `json:"status"`
	ZipCode        string             `json:"zip_code"`
	AddressLine    string             `json:"address_line"`
	Number         string             `json:"number"`
	Complement     *string            `json:"complement"`
	District       string             `json:"district"`
	City           string             `json:"city"`
	State          string             `json:"state"`
	Reference      *string            `json:"reference"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Availability struct {
	ID             pgtype.UUID        `json:"id"`
	ProfessionalID pgtype.UUID        `json:"professional_id"`
	DayOfWeek      string             `json:"day_of_week"`
	Shift          string             `json:"shift"`
	StartHour      *string            `json:"start_hour"`
	EndHour        *string            `json:"end_hour"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Contract struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
}

type Professional struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	LicenseNumber     *string          `json:"license_number"`
	Category          string           `json:"category"`
	YearsOfExperience *int32           `json:"years_of_experience"`
	Verified          bool             `json:"verified"`
	Resume            *string          `json:"resume"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Review struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	ContractID     pgtype.UUID      `json:"contract_id"`
	Rating         int32            `json:"rating"`
	Comment        *string          `json:"comment"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Phone     *string          `json:"phone"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
