// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: booking_request.sql

package bookingrequestpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBookingRequest = `-- name: CreateBookingRequest :one
INSERT INTO booking_requests (
  client_id, professional_id, address_id, proposed_value, schedule_details
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, client_id, professional_id, address_id, proposed_value, schedule_details, status, rejection_reason, created_at, responded_at
`

type CreateBookingRequestParams struct {
	ClientID        pgtype.UUID    `json:"client_id"`
	ProfessionalID  pgtype.UUID    `json:"professional_id"`
	AddressID       pgtype.UUID    `json:"address_id"`
	ProposedValue   pgtype.Numeric `json:"proposed_value"`
	ScheduleDetails []byte         `json:"schedule_details"`
}

func (q *Queries) CreateBookingRequest(ctx context.Context, arg CreateBookingRequestParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, createBookingRequest,
		arg.ClientID,
		arg.ProfessionalID,
		arg.AddressID,
		arg.ProposedValue,
		arg.ScheduleDetails,
	)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.AddressID,
		&i.ProposedValue,
		&i.ScheduleDetails,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getBookingRequestByID = `-- name: GetBookingRequestByID :one
SELECT id, client_id, professional_id, address_id, proposed_value, schedule_details, status, rejection_reason, created_at, responded_at
FROM booking_requests
WHERE id = $1
`

func (q *Queries) GetBookingRequestByID(ctx context.Context, id pgtype.UUID) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, getBookingRequestByID, id)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.AddressID,
		&i.ProposedValue,
		&i.ScheduleDetails,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getBookingRequestsByClientID = `-- name: GetBookingRequestsByClientID :many
SELECT id, client_id, professional_id, address_id, proposed_value, schedule_details, status, rejection_reason, created_at, responded_at
FROM booking_requests
WHERE client_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBookingRequestsByClientID(ctx context.Context, clientID pgtype.UUID) ([]BookingRequest, error) {
	rows, err := q.db.Query(ctx, getBookingRequestsByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingRequest
	for rows.Next() {
		var i BookingRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.AddressID,
			&i.ProposedValue,
			&i.ScheduleDetails,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingRequestsByProfessionalID = `-- name: GetBookingRequestsByProfessionalID :many
SELECT id, client_id, professional_id, address_id, proposed_value, schedule_details, status, rejection_reason, created_at, responded_at
FROM booking_requests
WHERE professional_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBookingRequestsByProfessionalID(ctx context.Context, professionalID pgtype.UUID) ([]BookingRequest, error) {
	rows, err := q.db.Query(ctx, getBookingRequestsByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingRequest
	for rows.Next() {
		var i BookingRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.AddressID,
			&i.ProposedValue,
			&i.ScheduleDetails,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingRequestStatus = `-- name: UpdateBookingRequestStatus :one
UPDATE booking_requests
SET status           = $1,
    rejection_reason = $2,
    responded_at     = NOW()
WHERE id = $3
RETURNING id, client_id, professional_id, address_id, proposed_value, schedule_details, status, rejection_reason, created_at, responded_at
`

type UpdateBookingRequestStatusParams struct {
	Status          string      `json:"status"`
	RejectionReason *string     `json:"rejection_reason"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBookingRequestStatus(ctx context.Context, arg UpdateBookingRequestStatusParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, updateBookingRequestStatus, arg.Status, arg.RejectionReason, arg.ID)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.AddressID,
		&i.ProposedValue,
		&i.ScheduleDetails,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}
