// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package userpostgres

import (
	"github.com/diegoHDCz/ajudafio/internal/user/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    domain.UserID    `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                domain.UserID    `json:"user_id"`
	AccessToken           *string          `json:"access_token"`
	RefreshToken          *string          `json:"refresh_token"`
	IDToken               *string          `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 *string          `json:"scope"`
	Password              *string          `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Address struct {
	ID          domain.UserID    `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	ContractID  pgtype.UUID      `json:"contract_id"`
	ZipCode     string           `json:"zip_code"`
	AddressLine string           `json:"address_line"`
	Number      string           `json:"number"`
	Complement  *string          `json:"complement"`
	District    string           `json:"district"`
	City        string           `json:"city"`
	State       string           `json:"state"`
	Reference   *string          `json:"reference"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Availability struct {
	ID             domain.UserID `json:"id"`
	ProfessionalID domain.UserID `json:"professional_id"`
	DayOfWeek      string        `json:"day_of_week"`
	Shift          *string       `json:"shift"`
	StartHour      *string       `json:"start_hour"`
	EndHour        *string       `json:"end_hour"`
}

type Contract struct {
	ID             domain.UserID    `json:"id"`
	ClientID       domain.UserID    `json:"client_id"`
	ProfessionalID domain.UserID    `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Professional struct {
	ID                domain.UserID    `json:"id"`
	UserID            domain.UserID    `json:"user_id"`
	LicenseNumber     *string          `json:"license_number"`
	Category          string           `json:"category"`
	YearsOfExperience *int32           `json:"years_of_experience"`
	Verified          bool             `json:"verified"`
	Resume            *string          `json:"resume"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Review struct {
	ID             domain.UserID    `json:"id"`
	ClientID       domain.UserID    `json:"client_id"`
	ProfessionalID domain.UserID    `json:"professional_id"`
	ContractID     pgtype.UUID      `json:"contract_id"`
	Rating         int32            `json:"rating"`
	Comment        *string          `json:"comment"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID        domain.UserID    `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IpAddress *string          `json:"ip_address"`
	UserAgent *string          `json:"user_agent"`
	UserID    domain.UserID    `json:"user_id"`
}

type User struct {
	ID                      domain.UserID    `json:"id"`
	Email                   string           `json:"email"`
	Name                    *string          `json:"name"`
	EmailVerified           bool             `json:"email_verified"`
	Image                   *string          `json:"image"`
	Telephone               *string          `json:"telephone"`
	TelephoneWhatsapp       bool             `json:"telephone_whatsapp"`
	SecondTelephone         *string          `json:"second_telephone"`
	SecondTelephoneWhatsapp bool             `json:"second_telephone_whatsapp"`
	Linkedin                *string          `json:"linkedin"`
	Instagram               *string          `json:"instagram"`
	Facebook                *string          `json:"facebook"`
	IdentificationNumber    *string          `json:"identification_number"`
	IdentificationType      *string          `json:"identification_type"`
	Role                    string           `json:"role"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}

type Verification struct {
	ID         domain.UserID    `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
