// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package userpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :one
INSERT INTO user_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT (user_id, role) DO NOTHING
RETURNING id, user_id, role, created_at
`

type AddUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, addUserRole, arg.UserID, arg.Role)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  auth_user_id,
  name,
  email,
  phone,
  role
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, auth_user_id, name, email, phone, role, onboarding_status, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	ID         pgtype.UUID `json:"id"`
	AuthUserID pgtype.UUID `json:"auth_user_id"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Phone      *string     `json:"phone"`
	Role       string      `json:"role"`
}

type CreateUserRow struct {
	ID               pgtype.UUID      `json:"id"`
	AuthUserID       pgtype.UUID      `json:"auth_user_id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	Phone            *string          `json:"phone"`
	Role             string           `json:"role"`
	OnboardingStatus string           `json:"onboarding_status"`
	AvatarUrl        *string          `json:"avatar_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.AuthUserID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnboardingStatus,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findOrCreateUserByAuthUserID = `-- name: FindOrCreateUserByAuthUserID :one
INSERT INTO users (id, auth_user_id, name, email, phone, role)
VALUES ($1, $2, $3, $4, NULL, $5)
ON CONFLICT (email) DO UPDATE SET
  auth_user_id = COALESCE(users.auth_user_id, EXCLUDED.auth_user_id),
  updated_at   = NOW()
RETURNING id, auth_user_id, name, email, phone, role, onboarding_status, avatar_url, created_at, updated_at
`

type FindOrCreateUserByAuthUserIDParams struct {
	ID         pgtype.UUID `json:"id"`
	AuthUserID pgtype.UUID `json:"auth_user_id"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Role       string      `json:"role"`
}

type FindOrCreateUserByAuthUserIDRow struct {
	ID               pgtype.UUID      `json:"id"`
	AuthUserID       pgtype.UUID      `json:"auth_user_id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	Phone            *string          `json:"phone"`
	Role             string           `json:"role"`
	OnboardingStatus string           `json:"onboarding_status"`
	AvatarUrl        *string          `json:"avatar_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

// Links a Supabase auth_user_id to an existing app user matched by email, or
// creates a fresh one. Race-safe: two concurrent first-access requests for the
// same brand-new email both converge on the same row via ON CONFLICT (email).
func (q *Queries) FindOrCreateUserByAuthUserID(ctx context.Context, arg FindOrCreateUserByAuthUserIDParams) (FindOrCreateUserByAuthUserIDRow, error) {
	row := q.db.QueryRow(ctx, findOrCreateUserByAuthUserID,
		arg.ID,
		arg.AuthUserID,
		arg.Name,
		arg.Email,
		arg.Role,
	)
	var i FindOrCreateUserByAuthUserIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnboardingStatus,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuthUserID = `-- name: GetUserByAuthUserID :one
SELECT id, auth_user_id, name, email, phone, role, onboarding_status, avatar_url, created_at, updated_at
FROM users
WHERE auth_user_id = $1
LIMIT 1
`

type GetUserByAuthUserIDRow struct {
	ID               pgtype.UUID      `json:"id"`
	AuthUserID       pgtype.UUID      `json:"auth_user_id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	Phone            *string          `json:"phone"`
	Role             string           `json:"role"`
	OnboardingStatus string           `json:"onboarding_status"`
	AvatarUrl        *string          `json:"avatar_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByAuthUserID(ctx context.Context, authUserID pgtype.UUID) (GetUserByAuthUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthUserID, authUserID)
	var i GetUserByAuthUserIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnboardingStatus,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, auth_user_id, name, email, phone, role, onboarding_status, avatar_url, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID               pgtype.UUID      `json:"id"`
	AuthUserID       pgtype.UUID      `json:"auth_user_id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	Phone            *string          `json:"phone"`
	Role             string           `json:"role"`
	OnboardingStatus string           `json:"onboarding_status"`
	AvatarUrl        *string          `json:"avatar_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnboardingStatus,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth_user_id, name, email, phone, role, onboarding_status, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID               pgtype.UUID      `json:"id"`
	AuthUserID       pgtype.UUID      `json:"auth_user_id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	Phone            *string          `json:"phone"`
	Role             string           `json:"role"`
	OnboardingStatus string           `json:"onboarding_status"`
	AvatarUrl        *string          `json:"avatar_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnboardingStatus,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesByUserID = `-- name: ListRolesByUserID :many
SELECT id, user_id, role, created_at
FROM user_roles
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListRolesByUserID(ctx context.Context, userID pgtype.UUID) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, listRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOnboardingStatus = `-- name: UpdateOnboardingStatus :exec
UPDATE users SET
  onboarding_status = $1,
  updated_at        = NOW()
WHERE id = $2
`

type UpdateOnboardingStatusParams struct {
	OnboardingStatus string      `json:"onboarding_status"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOnboardingStatus(ctx context.Context, arg UpdateOnboardingStatusParams) error {
	_, err := q.db.Exec(ctx, updateOnboardingStatus, arg.OnboardingStatus, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  name       = COALESCE($1, name),
  email      = COALESCE($2, email),
  phone      = COALESCE($3, phone),
  role       = COALESCE($4, role),
  updated_at = NOW()
WHERE id = $5
RETURNING id, auth_user_id, name, email, phone, role, onboarding_status, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	Name  string      `json:"name"`
	Email string      `json:"email"`
	Phone *string     `json:"phone"`
	Role  string      `json:"role"`
	ID    pgtype.UUID `json:"id"`
}

type UpdateUserRow struct {
	ID               pgtype.UUID      `json:"id"`
	AuthUserID       pgtype.UUID      `json:"auth_user_id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	Phone            *string          `json:"phone"`
	Role             string           `json:"role"`
	OnboardingStatus string           `json:"onboarding_status"`
	AvatarUrl        *string          `json:"avatar_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnboardingStatus,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET
  avatar_url = $1,
  updated_at = NOW()
WHERE id = $2
RETURNING id, auth_user_id, name, email, phone, role, onboarding_status, avatar_url, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	AvatarUrl *string     `json:"avatar_url"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateUserAvatarRow struct {
	ID               pgtype.UUID      `json:"id"`
	AuthUserID       pgtype.UUID      `json:"auth_user_id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	Phone            *string          `json:"phone"`
	Role             string           `json:"role"`
	OnboardingStatus string           `json:"onboarding_status"`
	AvatarUrl        *string          `json:"avatar_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UpdateUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	var i UpdateUserAvatarRow
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnboardingStatus,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET
  role       = $1,
  updated_at = NOW()
WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role string      `json:"role"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
