// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package userpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  name,
  email,
  phone,
  role
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, name, email, phone, role, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
	Phone *string     `json:"phone"`
	Role  string      `json:"role"`
}

type CreateUserRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Phone     *string          `json:"phone"`
	Role      string           `json:"role"`
	AvatarUrl *string          `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, role, avatar_url, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Phone     *string          `json:"phone"`
	Role      string           `json:"role"`
	AvatarUrl *string          `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, role, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Phone     *string          `json:"phone"`
	Role      string           `json:"role"`
	AvatarUrl *string          `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  name       = COALESCE($1, name),
  email      = COALESCE($2, email),
  phone      = COALESCE($3, phone),
  role       = COALESCE($4, role),
  updated_at = NOW()
WHERE id = $5
RETURNING id, name, email, phone, role, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	Name  string      `json:"name"`
	Email string      `json:"email"`
	Phone *string     `json:"phone"`
	Role  string      `json:"role"`
	ID    pgtype.UUID `json:"id"`
}

type UpdateUserRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Phone     *string          `json:"phone"`
	Role      string           `json:"role"`
	AvatarUrl *string          `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET
  avatar_url = $1,
  updated_at = NOW()
WHERE id = $2
RETURNING id, name, email, phone, role, avatar_url, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	AvatarUrl *string     `json:"avatar_url"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateUserAvatarRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Phone     *string          `json:"phone"`
	Role      string           `json:"role"`
	AvatarUrl *string          `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UpdateUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	var i UpdateUserAvatarRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET
  role       = $1,
  updated_at = NOW()
WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role string      `json:"role"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
