// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: avalability.sql

package availabilitypostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfessionalAvailability = `-- name: CreateProfessionalAvailability :one
INSERT INTO availabilities (professional_id, day_of_week, shift, start_hour, end_hour)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, professional_id, day_of_week, shift, start_hour, end_hour
`

type CreateProfessionalAvailabilityParams struct {
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      string      `json:"day_of_week"`
	Shift          *string     `json:"shift"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

type CreateProfessionalAvailabilityRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      string      `json:"day_of_week"`
	Shift          *string     `json:"shift"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) CreateProfessionalAvailability(ctx context.Context, arg CreateProfessionalAvailabilityParams) (CreateProfessionalAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, createProfessionalAvailability,
		arg.ProfessionalID,
		arg.DayOfWeek,
		arg.Shift,
		arg.StartHour,
		arg.EndHour,
	)
	var i CreateProfessionalAvailabilityRow
	err := row.Scan(
		&i.ID,
		&i.ProfessionalID,
		&i.DayOfWeek,
		&i.Shift,
		&i.StartHour,
		&i.EndHour,
	)
	return i, err
}

const deleteAvailabilitiesByProfessionalID = `-- name: DeleteAvailabilitiesByProfessionalID :exec
DELETE FROM availabilities WHERE professional_id = $1
`

func (q *Queries) DeleteAvailabilitiesByProfessionalID(ctx context.Context, professionalID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvailabilitiesByProfessionalID, professionalID)
	return err
}

const deleteProfessionalAvailability = `-- name: DeleteProfessionalAvailability :exec
DELETE FROM availabilities WHERE id = $1
`

func (q *Queries) DeleteProfessionalAvailability(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfessionalAvailability, id)
	return err
}

const getAllProfessionalAvailabilities = `-- name: GetAllProfessionalAvailabilities :many
SELECT a.id, a.professional_id, a.day_of_week, a.shift, a.start_hour, a.end_hour
FROM availabilities a
INNER JOIN professionals p ON a.professional_id = p.id
WHERE
    p.is_active = true
    AND ($1::text IS NULL OR a.day_of_week = $1::text)
    AND ($2::text IS NULL OR a.shift = $2::text)
    AND ($3::text IS NULL OR EXISTS (
        SELECT 1 FROM addresses ad
        WHERE ad.user_id = p.user_id AND ad.city = $3::text
    ))
`

type GetAllProfessionalAvailabilitiesParams struct {
	DayOfWeek *string `json:"day_of_week"`
	Shift     *string `json:"shift"`
	City      *string `json:"city"`
}

type GetAllProfessionalAvailabilitiesRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      string      `json:"day_of_week"`
	Shift          *string     `json:"shift"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) GetAllProfessionalAvailabilities(ctx context.Context, arg GetAllProfessionalAvailabilitiesParams) ([]GetAllProfessionalAvailabilitiesRow, error) {
	rows, err := q.db.Query(ctx, getAllProfessionalAvailabilities, arg.DayOfWeek, arg.Shift, arg.City)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProfessionalAvailabilitiesRow
	for rows.Next() {
		var i GetAllProfessionalAvailabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfessionalID,
			&i.DayOfWeek,
			&i.Shift,
			&i.StartHour,
			&i.EndHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityByID = `-- name: GetAvailabilityByID :one
SELECT id, professional_id, day_of_week, shift, start_hour, end_hour
FROM availabilities
WHERE id = $1
`

type GetAvailabilityByIDRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      string      `json:"day_of_week"`
	Shift          *string     `json:"shift"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) GetAvailabilityByID(ctx context.Context, id pgtype.UUID) (GetAvailabilityByIDRow, error) {
	row := q.db.QueryRow(ctx, getAvailabilityByID, id)
	var i GetAvailabilityByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProfessionalID,
		&i.DayOfWeek,
		&i.Shift,
		&i.StartHour,
		&i.EndHour,
	)
	return i, err
}

const getProfessionalAvailabilityByProfessionalID = `-- name: GetProfessionalAvailabilityByProfessionalID :many
SELECT id, professional_id, day_of_week, shift, start_hour, end_hour
FROM availabilities
WHERE professional_id = $1
`

type GetProfessionalAvailabilityByProfessionalIDRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      string      `json:"day_of_week"`
	Shift          *string     `json:"shift"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) GetProfessionalAvailabilityByProfessionalID(ctx context.Context, professionalID pgtype.UUID) ([]GetProfessionalAvailabilityByProfessionalIDRow, error) {
	rows, err := q.db.Query(ctx, getProfessionalAvailabilityByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfessionalAvailabilityByProfessionalIDRow
	for rows.Next() {
		var i GetProfessionalAvailabilityByProfessionalIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfessionalID,
			&i.DayOfWeek,
			&i.Shift,
			&i.StartHour,
			&i.EndHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfessionalAvailability = `-- name: UpdateProfessionalAvailability :one
UPDATE availabilities SET
    day_of_week = COALESCE($1, day_of_week),
    shift       = COALESCE($2, shift),
    start_hour  = COALESCE($3, start_hour),
    end_hour    = COALESCE($4, end_hour),
    updated_at  = NOW()
WHERE id = $5
RETURNING id, professional_id, day_of_week, shift, start_hour, end_hour
`

type UpdateProfessionalAvailabilityParams struct {
	DayOfWeek *string     `json:"day_of_week"`
	Shift     *string     `json:"shift"`
	StartHour *string     `json:"start_hour"`
	EndHour   *string     `json:"end_hour"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateProfessionalAvailabilityRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      string      `json:"day_of_week"`
	Shift          *string     `json:"shift"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) UpdateProfessionalAvailability(ctx context.Context, arg UpdateProfessionalAvailabilityParams) (UpdateProfessionalAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, updateProfessionalAvailability,
		arg.DayOfWeek,
		arg.Shift,
		arg.StartHour,
		arg.EndHour,
		arg.ID,
	)
	var i UpdateProfessionalAvailabilityRow
	err := row.Scan(
		&i.ID,
		&i.ProfessionalID,
		&i.DayOfWeek,
		&i.Shift,
		&i.StartHour,
		&i.EndHour,
	)
	return i, err
}
