// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: avalability.sql

package availabilitypostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfessionalAvailability = `-- name: CreateProfessionalAvailability :one
INSERT INTO availabilities (
    professional_id,
    day_of_week,
    start_hour,
    end_hour
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, professional_id, day_of_week, start_hour, end_hour
`

type CreateProfessionalAvailabilityParams struct {
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      []string    `json:"day_of_week"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

type CreateProfessionalAvailabilityRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      []string    `json:"day_of_week"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) CreateProfessionalAvailability(ctx context.Context, arg CreateProfessionalAvailabilityParams) (CreateProfessionalAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, createProfessionalAvailability,
		arg.ProfessionalID,
		arg.DayOfWeek,
		arg.StartHour,
		arg.EndHour,
	)
	var i CreateProfessionalAvailabilityRow
	err := row.Scan(
		&i.ID,
		&i.ProfessionalID,
		&i.DayOfWeek,
		&i.StartHour,
		&i.EndHour,
	)
	return i, err
}

const deleteProfessionalAvailability = `-- name: DeleteProfessionalAvailability :exec
DELETE FROM availabilities
WHERE id = $1
`

func (q *Queries) DeleteProfessionalAvailability(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfessionalAvailability, id)
	return err
}

const getAllProfessionalAvailabilities = `-- name: GetAllProfessionalAvailabilities :many

SELECT
    a.id,
    a.professional_id,
    a.day_of_week,
    a.start_hour,  
    a.end_hour
FROM
    availabilities a
INNER JOIN professionals p ON a.professional_id = p.id
WHERE
    p.is_active = true
    
    -- Filtro de DayOfWeek
    AND (cardinality($1::text[]) = 0 OR a.day_of_week = ANY($1::text[]))
    
    -- Filtro de Horário
    AND ($2::text IS NULL OR a.start_hour >= $2::text)
    AND ($3::text IS NULL OR a.end_hour <= $3::text)
    
    -- Filtro de Cidade
    AND ($4::text IS NULL OR EXISTS (
        SELECT 1
        FROM addresses ad
        WHERE ad.user_id = p.user_id
          AND ad.city = $4::text
    ))
`

type GetAllProfessionalAvailabilitiesParams struct {
	DayOfWeeks []string `json:"day_of_weeks"`
	StartTime  *string  `json:"start_time"`
	EndTime    *string  `json:"end_time"`
	City       *string  `json:"city"`
}

type GetAllProfessionalAvailabilitiesRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      []string    `json:"day_of_week"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

// Alterado de $1 para @professional_id para manter o padrão
func (q *Queries) GetAllProfessionalAvailabilities(ctx context.Context, arg GetAllProfessionalAvailabilitiesParams) ([]GetAllProfessionalAvailabilitiesRow, error) {
	rows, err := q.db.Query(ctx, getAllProfessionalAvailabilities,
		arg.DayOfWeeks,
		arg.StartTime,
		arg.EndTime,
		arg.City,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProfessionalAvailabilitiesRow
	for rows.Next() {
		var i GetAllProfessionalAvailabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfessionalID,
			&i.DayOfWeek,
			&i.StartHour,
			&i.EndHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfessionalAvailabilityByProfessionalID = `-- name: GetProfessionalAvailabilityByProfessionalID :many
SELECT
    a.id,
    a.professional_id,
    a.day_of_week,
    a.start_hour, -- Corrigido de start_time para start_hour
    a.end_hour   -- Corrigido de end_time para end_hour
FROM
    availabilities a  
WHERE 
    a.professional_id = $1
`

type GetProfessionalAvailabilityByProfessionalIDRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      []string    `json:"day_of_week"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) GetProfessionalAvailabilityByProfessionalID(ctx context.Context, professionalID pgtype.UUID) ([]GetProfessionalAvailabilityByProfessionalIDRow, error) {
	rows, err := q.db.Query(ctx, getProfessionalAvailabilityByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfessionalAvailabilityByProfessionalIDRow
	for rows.Next() {
		var i GetProfessionalAvailabilityByProfessionalIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfessionalID,
			&i.DayOfWeek,
			&i.StartHour,
			&i.EndHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfessionalAvailability = `-- name: UpdateProfessionalAvailability :one
UPDATE availabilities SET
    day_of_week = COALESCE($1, day_of_week),
    start_hour  = COALESCE($2, start_hour),
    end_hour    = COALESCE($3, end_hour)
WHERE id = $4
RETURNING id, professional_id, day_of_week, start_hour, end_hour
`

type UpdateProfessionalAvailabilityParams struct {
	DayOfWeek []string    `json:"day_of_week"`
	StartHour *string     `json:"start_hour"`
	EndHour   *string     `json:"end_hour"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateProfessionalAvailabilityRow struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      []string    `json:"day_of_week"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

func (q *Queries) UpdateProfessionalAvailability(ctx context.Context, arg UpdateProfessionalAvailabilityParams) (UpdateProfessionalAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, updateProfessionalAvailability,
		arg.DayOfWeek,
		arg.StartHour,
		arg.EndHour,
		arg.ID,
	)
	var i UpdateProfessionalAvailabilityRow
	err := row.Scan(
		&i.ID,
		&i.ProfessionalID,
		&i.DayOfWeek,
		&i.StartHour,
		&i.EndHour,
	)
	return i, err
}
