// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contract.sql

package contractpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (
  client_id,
  professional_id,
  hour_rate,
  total_amount,
  details,
  week_days,
  shift,
  start_time,
  hours_per_day,
  total_hours
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
`

type CreateContractParams struct {
	ClientID       pgtype.UUID `json:"client_id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	HourRate       int32       `json:"hour_rate"`
	TotalAmount    int32       `json:"total_amount"`
	Details        []byte      `json:"details"`
	WeekDays       []string    `json:"week_days"`
	Shift          *string     `json:"shift"`
	StartTime      pgtype.Time `json:"start_time"`
	HoursPerDay    int32       `json:"hours_per_day"`
	TotalHours     int32       `json:"total_hours"`
}

type CreateContractRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (CreateContractRow, error) {
	row := q.db.QueryRow(ctx, createContract,
		arg.ClientID,
		arg.ProfessionalID,
		arg.HourRate,
		arg.TotalAmount,
		arg.Details,
		arg.WeekDays,
		arg.Shift,
		arg.StartTime,
		arg.HoursPerDay,
		arg.TotalHours,
	)
	var i CreateContractRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.Status,
		&i.HourRate,
		&i.TotalAmount,
		&i.Details,
		&i.WeekDays,
		&i.Shift,
		&i.StartTime,
		&i.HoursPerDay,
		&i.TotalHours,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContract = `-- name: DeleteContract :exec
DELETE FROM contracts
WHERE id = $1
`

func (q *Queries) DeleteContract(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContract, id)
	return err
}

const getAllContracts = `-- name: GetAllContracts :many
SELECT id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
FROM contracts
ORDER BY created_at DESC
`

type GetAllContractsRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllContracts(ctx context.Context) ([]GetAllContractsRow, error) {
	rows, err := q.db.Query(ctx, getAllContracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllContractsRow
	for rows.Next() {
		var i GetAllContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Status,
			&i.HourRate,
			&i.TotalAmount,
			&i.Details,
			&i.WeekDays,
			&i.Shift,
			&i.StartTime,
			&i.HoursPerDay,
			&i.TotalHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllContractsByProfessionalCategory = `-- name: GetAllContractsByProfessionalCategory :many
SELECT c.id, c.client_id, c.professional_id, c.status, c.hour_rate, c.total_amount, c.details, c.week_days, c.shift, c.start_time, c.hours_per_day, c.total_hours, c.created_at
FROM contracts c
JOIN professionals p ON c.professional_id = p.id
WHERE p.category = $1
ORDER BY c.created_at DESC
`

type GetAllContractsByProfessionalCategoryRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllContractsByProfessionalCategory(ctx context.Context, category string) ([]GetAllContractsByProfessionalCategoryRow, error) {
	rows, err := q.db.Query(ctx, getAllContractsByProfessionalCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllContractsByProfessionalCategoryRow
	for rows.Next() {
		var i GetAllContractsByProfessionalCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Status,
			&i.HourRate,
			&i.TotalAmount,
			&i.Details,
			&i.WeekDays,
			&i.Shift,
			&i.StartTime,
			&i.HoursPerDay,
			&i.TotalHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllContractsByProfessionalID = `-- name: GetAllContractsByProfessionalID :many
SELECT id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
FROM contracts
WHERE professional_id = $1
ORDER BY created_at DESC
`

type GetAllContractsByProfessionalIDRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllContractsByProfessionalID(ctx context.Context, professionalID pgtype.UUID) ([]GetAllContractsByProfessionalIDRow, error) {
	rows, err := q.db.Query(ctx, getAllContractsByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllContractsByProfessionalIDRow
	for rows.Next() {
		var i GetAllContractsByProfessionalIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Status,
			&i.HourRate,
			&i.TotalAmount,
			&i.Details,
			&i.WeekDays,
			&i.Shift,
			&i.StartTime,
			&i.HoursPerDay,
			&i.TotalHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllContractsByProfessionalIDAndStatus = `-- name: GetAllContractsByProfessionalIDAndStatus :many
SELECT id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
FROM contracts
WHERE professional_id = $1
  AND status = $2
ORDER BY created_at DESC
`

type GetAllContractsByProfessionalIDAndStatusParams struct {
	ProfessionalID pgtype.UUID `json:"professional_id"`
	Status         string      `json:"status"`
}

type GetAllContractsByProfessionalIDAndStatusRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllContractsByProfessionalIDAndStatus(ctx context.Context, arg GetAllContractsByProfessionalIDAndStatusParams) ([]GetAllContractsByProfessionalIDAndStatusRow, error) {
	rows, err := q.db.Query(ctx, getAllContractsByProfessionalIDAndStatus, arg.ProfessionalID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllContractsByProfessionalIDAndStatusRow
	for rows.Next() {
		var i GetAllContractsByProfessionalIDAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Status,
			&i.HourRate,
			&i.TotalAmount,
			&i.Details,
			&i.WeekDays,
			&i.Shift,
			&i.StartTime,
			&i.HoursPerDay,
			&i.TotalHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllContractsByStatus = `-- name: GetAllContractsByStatus :many
SELECT id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
FROM contracts
WHERE status = $1
ORDER BY created_at DESC
`

type GetAllContractsByStatusRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllContractsByStatus(ctx context.Context, status string) ([]GetAllContractsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getAllContractsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllContractsByStatusRow
	for rows.Next() {
		var i GetAllContractsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Status,
			&i.HourRate,
			&i.TotalAmount,
			&i.Details,
			&i.WeekDays,
			&i.Shift,
			&i.StartTime,
			&i.HoursPerDay,
			&i.TotalHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllContractsByUserIDAndStatus = `-- name: GetAllContractsByUserIDAndStatus :many
SELECT id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
FROM contracts
WHERE client_id = $1
  AND status = $2
ORDER BY created_at DESC
`

type GetAllContractsByUserIDAndStatusParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Status   string      `json:"status"`
}

type GetAllContractsByUserIDAndStatusRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAllContractsByUserIDAndStatus(ctx context.Context, arg GetAllContractsByUserIDAndStatusParams) ([]GetAllContractsByUserIDAndStatusRow, error) {
	rows, err := q.db.Query(ctx, getAllContractsByUserIDAndStatus, arg.ClientID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllContractsByUserIDAndStatusRow
	for rows.Next() {
		var i GetAllContractsByUserIDAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Status,
			&i.HourRate,
			&i.TotalAmount,
			&i.Details,
			&i.WeekDays,
			&i.Shift,
			&i.StartTime,
			&i.HoursPerDay,
			&i.TotalHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContractByID = `-- name: GetContractByID :one
SELECT id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
FROM contracts
WHERE id = $1
LIMIT 1
`

type GetContractByIDRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetContractByID(ctx context.Context, id pgtype.UUID) (GetContractByIDRow, error) {
	row := q.db.QueryRow(ctx, getContractByID, id)
	var i GetContractByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.Status,
		&i.HourRate,
		&i.TotalAmount,
		&i.Details,
		&i.WeekDays,
		&i.Shift,
		&i.StartTime,
		&i.HoursPerDay,
		&i.TotalHours,
		&i.CreatedAt,
	)
	return i, err
}

const getContractsByUserID = `-- name: GetContractsByUserID :many
SELECT id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
FROM contracts
WHERE client_id = $1
ORDER BY created_at DESC
`

type GetContractsByUserIDRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetContractsByUserID(ctx context.Context, clientID pgtype.UUID) ([]GetContractsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getContractsByUserID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContractsByUserIDRow
	for rows.Next() {
		var i GetContractsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ProfessionalID,
			&i.Status,
			&i.HourRate,
			&i.TotalAmount,
			&i.Details,
			&i.WeekDays,
			&i.Shift,
			&i.StartTime,
			&i.HoursPerDay,
			&i.TotalHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContract = `-- name: UpdateContract :one
UPDATE contracts SET
  status       = COALESCE($1, status),
  hour_rate    = COALESCE($2, hour_rate),
  total_amount = COALESCE($3, total_amount),
  details      = COALESCE($4, details),
  week_days    = COALESCE($5, week_days),
  shift        = COALESCE($6, shift),
  start_time   = COALESCE($7, start_time),
  hours_per_day = COALESCE($8, hours_per_day),
  total_hours  = COALESCE($9, total_hours)
WHERE id = $10
RETURNING id, client_id, professional_id, status, hour_rate, total_amount, details, week_days, shift, start_time, hours_per_day, total_hours, created_at
`

type UpdateContractParams struct {
	Status      *string     `json:"status"`
	HourRate    *int32      `json:"hour_rate"`
	TotalAmount *int32      `json:"total_amount"`
	Details     []byte      `json:"details"`
	WeekDays    []string    `json:"week_days"`
	Shift       *string     `json:"shift"`
	StartTime   pgtype.Time `json:"start_time"`
	HoursPerDay *int32      `json:"hours_per_day"`
	TotalHours  *int32      `json:"total_hours"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateContractRow struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	WeekDays       []string         `json:"week_days"`
	Shift          *string          `json:"shift"`
	StartTime      pgtype.Time      `json:"start_time"`
	HoursPerDay    int32            `json:"hours_per_day"`
	TotalHours     int32            `json:"total_hours"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) UpdateContract(ctx context.Context, arg UpdateContractParams) (UpdateContractRow, error) {
	row := q.db.QueryRow(ctx, updateContract,
		arg.Status,
		arg.HourRate,
		arg.TotalAmount,
		arg.Details,
		arg.WeekDays,
		arg.Shift,
		arg.StartTime,
		arg.HoursPerDay,
		arg.TotalHours,
		arg.ID,
	)
	var i UpdateContractRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.Status,
		&i.HourRate,
		&i.TotalAmount,
		&i.Details,
		&i.WeekDays,
		&i.Shift,
		&i.StartTime,
		&i.HoursPerDay,
		&i.TotalHours,
		&i.CreatedAt,
	)
	return i, err
}
