// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile.sql

package profilepostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFamilyProfile = `-- name: CreateFamilyProfile :one
INSERT INTO family_profiles (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateFamilyProfile(ctx context.Context, userID pgtype.UUID) (FamilyProfile, error) {
	row := q.db.QueryRow(ctx, createFamilyProfile, userID)
	var i FamilyProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFinancialProfile = `-- name: CreateFinancialProfile :one
INSERT INTO financial_profiles (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateFinancialProfile(ctx context.Context, userID pgtype.UUID) (FinancialProfile, error) {
	row := q.db.QueryRow(ctx, createFinancialProfile, userID)
	var i FinancialProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFamilyProfileByUserID = `-- name: GetFamilyProfileByUserID :one
SELECT id, user_id, created_at, updated_at
FROM family_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetFamilyProfileByUserID(ctx context.Context, userID pgtype.UUID) (FamilyProfile, error) {
	row := q.db.QueryRow(ctx, getFamilyProfileByUserID, userID)
	var i FamilyProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinancialProfileByUserID = `-- name: GetFinancialProfileByUserID :one
SELECT id, user_id, created_at, updated_at
FROM financial_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetFinancialProfileByUserID(ctx context.Context, userID pgtype.UUID) (FinancialProfile, error) {
	row := q.db.QueryRow(ctx, getFinancialProfileByUserID, userID)
	var i FinancialProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
