// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package authpostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (
    account_id, provider_id, user_id,
    access_token, refresh_token, id_token,
    access_token_expires_at, refresh_token_expires_at,
    scope, password, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NULL, NOW(), NOW()
)
RETURNING id, account_id, provider_id, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at
`

type CreateAccountParams struct {
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                pgtype.UUID      `json:"user_id"`
	AccessToken           *string          `json:"access_token"`
	RefreshToken          *string          `json:"refresh_token"`
	IDToken               *string          `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 *string          `json:"scope"`
}

// =============================================================================
// Accounts (provider links)
// =============================================================================
// Links a Keycloak account to a local user. password is always NULL for OIDC providers.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.AccountID,
		arg.ProviderID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.IDToken,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
		arg.Scope,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProviderID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (
    expires_at, token, created_at, updated_at, ip_address, user_agent, user_id
) VALUES (
    $1, $2, NOW(), NOW(), $3, $4, $5
)
RETURNING id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id
`

type CreateSessionParams struct {
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	IpAddress *string          `json:"ip_address"`
	UserAgent *string          `json:"user_agent"`
	UserID    pgtype.UUID      `json:"user_id"`
}

// =============================================================================
// Sessions
// =============================================================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ExpiresAt,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
	)
	return i, err
}

const createVerification = `-- name: CreateVerification :one

INSERT INTO verifications (
    identifier, value, expires_at, created_at, updated_at
) VALUES (
    $1, $2, $3, NOW(), NOW()
)
RETURNING id, identifier, value, expires_at, created_at, updated_at
`

type CreateVerificationParams struct {
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

// =============================================================================
// Verifications
// =============================================================================
func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification, arg.Identifier, arg.Value, arg.ExpiresAt)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM verifications
WHERE identifier = $1 AND value = $2
`

type DeleteVerificationParams struct {
	Identifier string `json:"identifier"`
	Value      string `json:"value"`
}

func (q *Queries) DeleteVerification(ctx context.Context, arg DeleteVerificationParams) error {
	_, err := q.db.Exec(ctx, deleteVerification, arg.Identifier, arg.Value)
	return err
}

const getAccountByProvider = `-- name: GetAccountByProvider :one
SELECT id, account_id, provider_id, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at FROM accounts
WHERE provider_id = $1 AND account_id = $2 LIMIT 1
`

type GetAccountByProviderParams struct {
	ProviderID string `json:"provider_id"`
	AccountID  string `json:"account_id"`
}

func (q *Queries) GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByProvider, arg.ProviderID, arg.AccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProviderID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Scope,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, account_id, provider_id, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at FROM accounts
WHERE user_id = $1
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProviderID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.IDToken,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.Scope,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id FROM sessions
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, role, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByKeycloakID = `-- name: GetUserByKeycloakID :one
SELECT
    u.id, u.name, u.email, u.phone, u.role, u.created_at, u.updated_at
FROM users u
JOIN accounts a ON a.user_id = u.id
WHERE a.provider_id = 'keycloak' AND a.account_id = $1
LIMIT 1
`

// Resolves a local user via the Keycloak subject (sub claim) stored in accounts.
func (q *Queries) GetUserByKeycloakID(ctx context.Context, accountID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKeycloakID, accountID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerification = `-- name: GetVerification :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM verifications
WHERE identifier = $1 AND value = $2 LIMIT 1
`

type GetVerificationParams struct {
	Identifier string `json:"identifier"`
	Value      string `json:"value"`
}

func (q *Queries) GetVerification(ctx context.Context, arg GetVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerification, arg.Identifier, arg.Value)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (name, email, role, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (email) DO UPDATE
    SET name       = EXCLUDED.name,
        updated_at = NOW()
RETURNING id, name, email, phone, role, created_at, updated_at
`

type UpsertUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

// =============================================================================
// Users
// =============================================================================
// Upserts a local user from Keycloak claims forwarded by KrakenD.
// On conflict by email, refreshes the name to reflect Keycloak profile changes.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Name, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
