// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package authpostgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    pgtype.UUID      `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                pgtype.UUID      `json:"user_id"`
	AccessToken           *string          `json:"access_token"`
	RefreshToken          *string          `json:"refresh_token"`
	IDToken               *string          `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 *string          `json:"scope"`
	Password              *string          `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Address struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	ContractID  pgtype.UUID      `json:"contract_id"`
	ZipCode     string           `json:"zip_code"`
	AddressLine string           `json:"address_line"`
	Number      string           `json:"number"`
	Complement  *string          `json:"complement"`
	District    string           `json:"district"`
	City        string           `json:"city"`
	State       string           `json:"state"`
	Reference   *string          `json:"reference"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Availability struct {
	ID             pgtype.UUID `json:"id"`
	ProfessionalID pgtype.UUID `json:"professional_id"`
	DayOfWeek      string      `json:"day_of_week"`
	Shift          *string     `json:"shift"`
	StartHour      *string     `json:"start_hour"`
	EndHour        *string     `json:"end_hour"`
}

type Contract struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	Status         string           `json:"status"`
	HourRate       int32            `json:"hour_rate"`
	TotalAmount    int32            `json:"total_amount"`
	Details        []byte           `json:"details"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Professional struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	LicenseNumber     *string          `json:"license_number"`
	Category          string           `json:"category"`
	YearsOfExperience *int32           `json:"years_of_experience"`
	Verified          bool             `json:"verified"`
	Resume            *string          `json:"resume"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Review struct {
	ID             pgtype.UUID      `json:"id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	ProfessionalID pgtype.UUID      `json:"professional_id"`
	ContractID     pgtype.UUID      `json:"contract_id"`
	Rating         int32            `json:"rating"`
	Comment        *string          `json:"comment"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID      `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IpAddress *string          `json:"ip_address"`
	UserAgent *string          `json:"user_agent"`
	UserID    pgtype.UUID      `json:"user_id"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Phone     *string          `json:"phone"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Verification struct {
	ID         pgtype.UUID      `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
