### -- Variables -------------------------------------------------------
@gatewayUrl  = http://localhost:8090
@keycloakUrl = http://localhost:8180
@baseUrl = http://localhost:8080
@realm       = ajudafio
@clientId    = ajudafio-frontend

@access_token = INSIRA O

###
GET {{baseUrl}}/users/me
Authorization: Bearer {{access_token}}


###
POST http://localhost:8180/admin/ajudafio/master/users
Content-Type: application/json
Authorization: Beraer {{access_token}}

{
  "username": "testuser",
  "enabled": true,
  "emailVerified": false,
  "firstName": "Test",
  "lastName": "User",
  "email": "
}