### -- Variables -------------------------------------------------------
@gatewayUrl  = http://localhost:8090
@keycloakUrl = http://localhost:8180
@baseUrl = http://localhost:8080
@realm       = ajudafio
@clientId    = ajudafio-frontend

@access_token = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zQXdJS1NHODJING4ydlU3bWFwcVVrYVNlSGsiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJlbWFpbCI6ImRpZWdvLmN6YWprYUBnbWFpbC5jb20iLCJleHAiOjE3ODA0MjkxMDksImZ1bGxfbmFtZSI6IkRpZWdvIEhlcm5hbiBEZW1pdHRvIEN6YWprYSIsImlhdCI6MTc4MDQyNTUwOSwiaWQiOiJ1c2VyXzNFWVNEOExEVDFsUk42ZjVOVTh1c1ZrUUdzbCIsImlzcyI6Imh0dHBzOi8vd2VsY29tZWQtdXJjaGluLTM0LmNsZXJrLmFjY291bnRzLmRldiIsImp0aSI6ImM1ZjZkYjNjZDgzNGU3ZjA4ZDY4IiwibGFzdF9zaWduX2luX2F0IjoxNzgwNDIxMTg0LCJtZXRhZGF0YSI6e30sIm5iZiI6MTc4MDQyNTUwNCwic3ViIjoidXNlcl8zRVlTRDhMRFQxbFJONmY1TlU4dXNWa1FHc2wifQ.YRYJF9MJHSIyV7vhuqWX1Nb6ntrqlUpfYwvu-nkKNs8BA9stHsF0LR7eYldSXw8sCC0Rykb5OonQlotFIF2YewFa86Bx8HDFUqW_MuU6enMpUixKJsYLK9kRbDagSkjmOy_pCGzYOqBnqIRuLuuHo0A2a92_QfAAAYQHJsPRiIR8iNWxqW4WWXAH6etGr_SUpUZkb21m8jYDomUufKyR9sulWieIx8JgvtuPa7bksrbfD_fpKw-Z3Y3fBlK43WKv9llfbuPdmp4pyM-k-2DOO9yUmJnzbsnTKpzchwgihmiB3AooWFuT9Fh-I5cjrTJFDZZV1IbQIM8EYAVu3fykpQ


###
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
POST http://localhost:8180/admin/ajudafio/master/users
Content-Type: application/json
Authorization: Beraer {{access_token}}

{
  "username": "testuser",
  "enabled": true,
  "emailVerified": false,
  "firstName": "Test",
  "lastName": "User",
  "email": "
}