// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: address.sql

package addresspostgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
  user_id,
  contract_id,
  zip_code,
  address_line,
  number,
  complement,
  district,
  city,
  state,
  reference
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id, user_id, contract_id, zip_code, address_line, number, complement, district, city, state, reference, created_at, updated_at
`

type CreateAddressParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ContractID  pgtype.UUID `json:"contract_id"`
	ZipCode     string      `json:"zip_code"`
	AddressLine string      `json:"address_line"`
	Number      string      `json:"number"`
	Complement  *string     `json:"complement"`
	District    string      `json:"district"`
	City        string      `json:"city"`
	State       string      `json:"state"`
	Reference   *string     `json:"reference"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.ContractID,
		arg.ZipCode,
		arg.AddressLine,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.Reference,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContractID,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses
WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, contract_id, zip_code, address_line, number, complement, district, city, state, reference, created_at, updated_at
FROM addresses
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAddressByID(ctx context.Context, id pgtype.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContractID,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressWithContract = `-- name: GetAddressWithContract :one
SELECT
  a.id,
  a.user_id,
  a.contract_id,
  a.zip_code,
  a.address_line,
  a.number,
  a.complement,
  a.district,
  a.city,
  a.state,
  a.reference,
  a.created_at,
  a.updated_at,
  c.client_id          AS contract_client_id,
  c.professional_id    AS contract_professional_id,
  c.status             AS contract_status,
  c.hour_rate          AS contract_hour_rate,
  c.total_amount       AS contract_total_amount,
  c.details            AS contract_details,
  c.created_at         AS contract_created_at
FROM addresses a
INNER JOIN contracts c ON c.id = a.contract_id
WHERE a.id = $1
LIMIT 1
`

type GetAddressWithContractRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	ContractID             pgtype.UUID      `json:"contract_id"`
	ZipCode                string           `json:"zip_code"`
	AddressLine            string           `json:"address_line"`
	Number                 string           `json:"number"`
	Complement             *string          `json:"complement"`
	District               string           `json:"district"`
	City                   string           `json:"city"`
	State                  string           `json:"state"`
	Reference              *string          `json:"reference"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	ContractClientID       pgtype.UUID      `json:"contract_client_id"`
	ContractProfessionalID pgtype.UUID      `json:"contract_professional_id"`
	ContractStatus         string           `json:"contract_status"`
	ContractHourRate       int32            `json:"contract_hour_rate"`
	ContractTotalAmount    int32            `json:"contract_total_amount"`
	ContractDetails        []byte           `json:"contract_details"`
	ContractCreatedAt      pgtype.Timestamp `json:"contract_created_at"`
}

func (q *Queries) GetAddressWithContract(ctx context.Context, id pgtype.UUID) (GetAddressWithContractRow, error) {
	row := q.db.QueryRow(ctx, getAddressWithContract, id)
	var i GetAddressWithContractRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContractID,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractClientID,
		&i.ContractProfessionalID,
		&i.ContractStatus,
		&i.ContractHourRate,
		&i.ContractTotalAmount,
		&i.ContractDetails,
		&i.ContractCreatedAt,
	)
	return i, err
}

const getAddressWithUser = `-- name: GetAddressWithUser :one
SELECT
  a.id,
  a.user_id,
  a.contract_id,
  a.zip_code,
  a.address_line,
  a.number,
  a.complement,
  a.district,
  a.city,
  a.state,
  a.reference,
  a.created_at,
  a.updated_at,
  u.name        AS user_name,
  u.email       AS user_email,
  u.phone       AS user_phone,
  u.role        AS user_role
FROM addresses a
INNER JOIN users u ON u.id = a.user_id
WHERE a.id = $1
LIMIT 1
`

type GetAddressWithUserRow struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	ContractID  pgtype.UUID      `json:"contract_id"`
	ZipCode     string           `json:"zip_code"`
	AddressLine string           `json:"address_line"`
	Number      string           `json:"number"`
	Complement  *string          `json:"complement"`
	District    string           `json:"district"`
	City        string           `json:"city"`
	State       string           `json:"state"`
	Reference   *string          `json:"reference"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	UserName    string           `json:"user_name"`
	UserEmail   string           `json:"user_email"`
	UserPhone   *string          `json:"user_phone"`
	UserRole    string           `json:"user_role"`
}

func (q *Queries) GetAddressWithUser(ctx context.Context, id pgtype.UUID) (GetAddressWithUserRow, error) {
	row := q.db.QueryRow(ctx, getAddressWithUser, id)
	var i GetAddressWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContractID,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
		&i.UserRole,
	)
	return i, err
}

const getAddressesByCity = `-- name: GetAddressesByCity :many
SELECT id, user_id, contract_id, zip_code, address_line, number, complement, district, city, state, reference, created_at, updated_at
FROM addresses
WHERE city = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAddressesByCity(ctx context.Context, city string) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAddressesByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContractID,
			&i.ZipCode,
			&i.AddressLine,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.Reference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAddressesByContractID = `-- name: GetAddressesByContractID :many
SELECT id, user_id, contract_id, zip_code, address_line, number, complement, district, city, state, reference, created_at, updated_at
FROM addresses
WHERE contract_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAddressesByContractID(ctx context.Context, contractID pgtype.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAddressesByContractID, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContractID,
			&i.ZipCode,
			&i.AddressLine,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.Reference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAddressesByUserID = `-- name: GetAddressesByUserID :many
SELECT id, user_id, contract_id, zip_code, address_line, number, complement, district, city, state, reference, created_at, updated_at
FROM addresses
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAddressesByUserID(ctx context.Context, userID pgtype.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContractID,
			&i.ZipCode,
			&i.AddressLine,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.Reference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAddresses = `-- name: GetAllAddresses :many
SELECT id, user_id, contract_id, zip_code, address_line, number, complement, district, city, state, reference, created_at, updated_at
FROM addresses
WHERE
  ($1::text    IS NULL OR zip_code    = $1::text)
  AND ($2::uuid     IS NULL OR user_id     = $2::uuid)
  AND ($3::text        IS NULL OR city        = $3::text)
  AND ($4::text    IS NULL OR district    = $4::text)
  AND ($5::text      IS NULL OR number      = $5::text)
  AND ($6::uuid IS NULL OR contract_id = $6::uuid)
ORDER BY created_at DESC
`

type GetAllAddressesParams struct {
	ZipCode    *string     `json:"zip_code"`
	UserID     pgtype.UUID `json:"user_id"`
	City       *string     `json:"city"`
	District   *string     `json:"district"`
	Number     *string     `json:"number"`
	ContractID pgtype.UUID `json:"contract_id"`
}

func (q *Queries) GetAllAddresses(ctx context.Context, arg GetAllAddressesParams) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAllAddresses,
		arg.ZipCode,
		arg.UserID,
		arg.City,
		arg.District,
		arg.Number,
		arg.ContractID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContractID,
			&i.ZipCode,
			&i.AddressLine,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.Reference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses SET
  zip_code     = COALESCE($1, zip_code),
  address_line = COALESCE($2, address_line),
  number       = COALESCE($3, number),
  complement   = COALESCE($4, complement),
  district     = COALESCE($5, district),
  city         = COALESCE($6, city),
  state        = COALESCE($7, state),
  reference    = COALESCE($8, reference),
  updated_at   = NOW()
WHERE id = $9
RETURNING id, user_id, contract_id, zip_code, address_line, number, complement, district, city, state, reference, created_at, updated_at
`

type UpdateAddressParams struct {
	ZipCode     *string     `json:"zip_code"`
	AddressLine *string     `json:"address_line"`
	Number      *string     `json:"number"`
	Complement  *string     `json:"complement"`
	District    *string     `json:"district"`
	City        *string     `json:"city"`
	State       *string     `json:"state"`
	Reference   *string     `json:"reference"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ZipCode,
		arg.AddressLine,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.Reference,
		arg.ID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContractID,
		&i.ZipCode,
		&i.AddressLine,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
